[M5Stack_Core2_LoRa868_v11_ENV4]
extends = esp32_base
board = m5stack-core2
board_build.partitions = default_16MB.csv
extra_scripts =
  ${esp32_base.extra_scripts}
  post:variants/m5stack_core2_lora868_v11_lan_poe_env4/patch_m5core2_i2c.py
build_flags =
  ${esp32_base.build_flags}
  -I variants/m5stack_core2_lora868_v11_lan_poe_env4
  -D ARDUINO_M5STACK_CORE2
  -D USE_SX1276
  -D RADIO_CLASS=CustomSX1276
  -D WRAPPER_CLASS=CustomSX1276Wrapper
  -D P_LORA_SCLK=18
  -D P_LORA_MISO=38
  -D P_LORA_MOSI=23
  -D P_LORA_NSS=27
  -D P_LORA_DIO_0=35
  -D P_LORA_DIO_1=-1
  -D P_LORA_RESET=25
  -D SX127X_CURRENT_LIMIT=120
  -D LORA_TX_POWER=20
  -D PIN_BOARD_SDA=21
  -D PIN_BOARD_SCL=22
  -D RTC_FIXED_PCF8563=1
  -D ENV_PIN_SDA=32
  -D ENV_PIN_SCL=33
  -D ENV_INCLUDE_BMP280=1
  -D ENV_INCLUDE_SHT4X=1
  -D ENV_INCLUDE_SGP30=1
build_src_filter = ${esp32_base.build_src_filter}
  +<../variants/m5stack_core2_lora868_v11_lan_poe_env4>
  +<helpers/sensors>
lib_deps =
  ${esp32_base.lib_deps}
  adafruit/Adafruit BMP280 Library @ ^3.0.0
  sensirion/Sensirion I2C SHT4x @ ^1.1.2
  adafruit/Adafruit SGP30 Sensor @ ^2.0.3
  m5stack/M5Core2 @ ^0.2.0

[env:M5Stack_Core2_LoRa868_v11_ENV4_repeater]
extends = M5Stack_Core2_LoRa868_v11_ENV4
build_flags =
  ${M5Stack_Core2_LoRa868_v11_ENV4.build_flags}
  -D ADVERT_NAME='"M5Core2 LoRa868 Repeater"'
  -D ADVERT_LAT=0.0
  -D ADVERT_LON=0.0
  -D ADMIN_PASSWORD='"password"'
  -D MAX_NEIGHBOURS=50
build_src_filter = ${M5Stack_Core2_LoRa868_v11_ENV4.build_src_filter}
  +<../examples/simple_repeater>
lib_deps =
  ${M5Stack_Core2_LoRa868_v11_ENV4.lib_deps}
  ${esp32_ota.lib_deps}

[env:M5Stack_Core2_LoRa868_v11_ENV4_room_server]
extends = M5Stack_Core2_LoRa868_v11_ENV4
build_src_filter = ${M5Stack_Core2_LoRa868_v11_ENV4.build_src_filter}
  +<../examples/simple_room_server>
build_flags =
  ${M5Stack_Core2_LoRa868_v11_ENV4.build_flags}
  -D ADVERT_NAME='"M5Core2 LoRa868 Room"'
  -D ADVERT_LAT=0.0
  -D ADVERT_LON=0.0
  -D ADMIN_PASSWORD='"password"'
  -D ROOM_PASSWORD='"hello"'
lib_deps =
  ${M5Stack_Core2_LoRa868_v11_ENV4.lib_deps}
  ${esp32_ota.lib_deps}

[env:M5Stack_Core2_LoRa868_v11_ENV4_companion_radio_usb]
extends = M5Stack_Core2_LoRa868_v11_ENV4
build_flags =
  ${M5Stack_Core2_LoRa868_v11_ENV4.build_flags}
  -D DISPLAY_CLASS=Core2M5Display
  -D CORE2_ALWAYS_POWERED=1
  -I examples/companion_radio/ui-new
  -D MAX_CONTACTS=175
  -D MAX_GROUP_CHANNELS=20
  -D OFFLINE_QUEUE_SIZE=32
  -D MAX_UNREAD_MSGS=8
build_src_filter = ${M5Stack_Core2_LoRa868_v11_ENV4.build_src_filter}
  +<helpers/esp32/*.cpp>
  +<../examples/companion_radio/*.cpp>
  +<../examples/companion_radio/ui-new/*.cpp>
lib_deps =
  ${M5Stack_Core2_LoRa868_v11_ENV4.lib_deps}
  densaugeo/base64 @ ~1.4.0

[env:M5Stack_Core2_LoRa868_v11_ENV4_companion_radio_ble]
extends = M5Stack_Core2_LoRa868_v11_ENV4
build_flags =
  ${M5Stack_Core2_LoRa868_v11_ENV4.build_flags}
  -D DISPLAY_CLASS=Core2M5Display
  -D CORE2_ALWAYS_POWERED=1
  -I examples/companion_radio/ui-new
  -D MAX_CONTACTS=175
  -D MAX_GROUP_CHANNELS=20
  -D BLE_PIN_CODE=123456
  -D BLE_DEBUG_LOGGING=0
  -D OFFLINE_QUEUE_SIZE=32
  -D MAX_UNREAD_MSGS=8
build_src_filter = ${M5Stack_Core2_LoRa868_v11_ENV4.build_src_filter}
  +<helpers/esp32/SerialBLEInterface.cpp>
  +<../examples/companion_radio/*.cpp>
  +<../examples/companion_radio/ui-new/*.cpp>
lib_deps =
  ${M5Stack_Core2_LoRa868_v11_ENV4.lib_deps}
  densaugeo/base64 @ ~1.4.0

[env:M5Stack_Core2_LoRa868_v11_ENV4_kiss_modem]
extends = M5Stack_Core2_LoRa868_v11_ENV4
build_src_filter = ${M5Stack_Core2_LoRa868_v11_ENV4.build_src_filter}
  +<../examples/kiss_modem/>

[env:M5Stack_Core2_LoRa868_v11_ENV4_simple_sensor]
extends = M5Stack_Core2_LoRa868_v11_ENV4
build_flags =
  ${M5Stack_Core2_LoRa868_v11_ENV4.build_flags}
  -D DISPLAY_CLASS=Core2M5Display
  -D CORE2_ALWAYS_POWERED=1
  -D SENSOR_READ_INTERVAL_SECS=60
build_src_filter = ${M5Stack_Core2_LoRa868_v11_ENV4.build_src_filter}
  +<../examples/simple_sensor>
