name: Build And Publish Firmware Artifacts (nRF52)

permissions:
  contents: read

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    uses: ./.github/workflows/build-and-publish-firmware-artifacts.yml
    with:
      platform_filter: NRF52_PLATFORM
      workflow_label: nRF52
    secrets: inherit
