name: Build And Publish Firmware Artifacts (ESP32)

permissions:
  contents: read

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    uses: ./.github/workflows/build-and-publish-firmware-artifacts.yml
    with:
      platform_filter: ESP32_PLATFORM
      workflow_label: ESP32
    secrets: inherit
