name: Manual Build And Publish Firmware Artifacts

on:
  workflow_dispatch:

jobs:
  call-build-and-publish:
    uses: ./.github/workflows/build-and-publish-firmware-artifacts.yml
    secrets: inherit
